"""Default configuration constants."""

from vibecast._config.loader import (
    _CONFIG_FILE_NAME,
    _DEFAULT_CAST_USER_AGENT,
    _DEFAULT_CONFIG_CONTENT,
)

CONFIG_FILE_NAME = _CONFIG_FILE_NAME
DEFAULT_CAST_USER_AGENT = _DEFAULT_CAST_USER_AGENT
DEFAULT_CONFIG_CONTENT = _DEFAULT_CONFIG_CONTENT

__all__ = [
    "CONFIG_FILE_NAME",
    "DEFAULT_CAST_USER_AGENT",
    "DEFAULT_CONFIG_CONTENT",
]
